// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcMB_aDnGZIE6X4tAZf7v3E641B2A6yCU',
    appId: '1:640921276858:web:66214481887129c0f10d83',
    messagingSenderId: '640921276858',
    projectId: 'controleaprovacao-cdfa9',
    authDomain: 'controleaprovacao-cdfa9.firebaseapp.com',
    storageBucket: 'controleaprovacao-cdfa9.appspot.com',
    measurementId: 'G-X9CELX5HH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzBuMPl5WaKvrcZyAVZ-XS7rnHiH9CWTI',
    appId: '1:640921276858:android:3c1307265e4dac1ef10d83',
    messagingSenderId: '640921276858',
    projectId: 'controleaprovacao-cdfa9',
    storageBucket: 'controleaprovacao-cdfa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfnCR_4HBTEAHQvuCrsPz_xbOLzljXlZs',
    appId: '1:640921276858:ios:b8a62d00d78e9389f10d83',
    messagingSenderId: '640921276858',
    projectId: 'controleaprovacao-cdfa9',
    storageBucket: 'controleaprovacao-cdfa9.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfnCR_4HBTEAHQvuCrsPz_xbOLzljXlZs',
    appId: '1:640921276858:ios:b8a62d00d78e9389f10d83',
    messagingSenderId: '640921276858',
    projectId: 'controleaprovacao-cdfa9',
    storageBucket: 'controleaprovacao-cdfa9.appspot.com',
    iosBundleId: 'com.example.untitled',
  );
}
